"""SQLAlchemy ORM model for security alerts generated by AI threat detection."""

from datetime import datetime, timezone
from sqlalchemy import (
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
)
from sqlalchemy.orm import relationship
from backend.app.db.session import Base


def utc_now() -> datetime:
    """Return timezone-aware current UTC time."""
    return datetime.now(timezone.utc)


class AlertRecord(Base):
    """High-priority incident notification generated for significant security events."""

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    prediction_id = Column(
        Integer,
        ForeignKey("prediction_records.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    timestamp = Column(DateTime(timezone=True), default=utc_now, index=True, nullable=False)

    alert_type = Column(String(50), nullable=False, default="NETWORK_INTRUSION")  # NETWORK_INTRUSION | ANOMALY_MONITORING | CRITICAL_INTRUSION
    severity = Column(String(20), nullable=False, index=True)  # LOW, MEDIUM, HIGH, CRITICAL
    threat_label = Column(String(50), nullable=False, index=True)
    anomaly_score = Column(Float, nullable=False)
    confidence = Column(Float, nullable=False)

    # Optional Network Endpoints
    source_ip = Column(String(45), nullable=True)
    destination_ip = Column(String(45), nullable=True)

    status = Column(String(30), default="NEW", index=True, nullable=False)  # NEW, ACKNOWLEDGED, RESOLVED, FALSE_POSITIVE
    recommended_action = Column(String(255), nullable=False)
    created_at = Column(DateTime(timezone=True), default=utc_now, index=True, nullable=False)
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    prediction = relationship("PredictionRecord", back_populates="alerts")
